In [1]:
import gym 
import numpy as np 
import tensorflow as tf

#Create and initialize a TensorFlow constant tensor
tensor = tf.constant ([[1, 2], [3, 4]])

#Print the tensor 
print("Tensor:") 
print(tensor)

#Create a TensorFlow variable and initialize it with zeros 
variable = tf.Variable(tf.zeros([2,2]))

#Print the variable 
print("\nvariable:") 
print(variable)

#Update the variable 
variable.assign_add(tf.ones([2,2]))

#Print the updated variable 
print("\nUpdated variable:") 
print(variable)

#Create an environment from OpenAI Gym 
env = gym.make('CartPole-v1')

#Initialize the environment 
state = env.reset()


Tensor:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

variable:
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

Updated variable:
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>


In [3]:
# Initialize the environment 
state = env.reset()

# Run the environment for 100 steps
for _ in range(100):
    # Render the environment
    env.render()

    # Take a random action 
    action = env.action_space.sample()

    # Perform the action in the environment
    result = env.step(action)
    print("Step Result:", result)

    # Unpack the returned values
    next_state, reward, done, info,_= result

    # If episode is finished, reset the environment
    if done:
        state = env.reset()

# Close the environment
env.close()


Step Result: (array([-2.6076470e-02, -2.0818603e-01,  1.7018568e-04,  2.9522514e-01],
      dtype=float32), 1.0, False, False, {})
Step Result: (array([-0.03024019, -0.0130665 ,  0.00607469,  0.0025959 ], dtype=float32), 1.0, False, False, {})
Step Result: (array([-0.03050152,  0.18196781,  0.00612661, -0.28816423], dtype=float32), 1.0, False, False, {})
Step Result: (array([-0.02686216, -0.01324098,  0.00036332,  0.00644467], dtype=float32), 1.0, False, False, {})
Step Result: (array([-0.02712698,  0.18187577,  0.00049222, -0.2861236 ], dtype=float32), 1.0, False, False, {})
Step Result: (array([-0.02348947, -0.0132532 , -0.00523026,  0.00671453], dtype=float32), 1.0, False, False, {})
Step Result: (array([-0.02375453,  0.18194336, -0.00509597, -0.28761402], dtype=float32), 1.0, False, False, {})
Step Result: (array([-0.02011566, -0.01310555, -0.01084825,  0.00345735], dtype=float32), 1.0, False, False, {})
Step Result: (array([-0.02037778, -0.20807025, -0.0107791 ,  0.29269788], dtyp

c:\Users\hp\anaconda3\Lib\site-packages\gym\envs\classic_control\cartpole.py:211: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v1", render_mode="rgb_array")
  gym.logger.warn(
